catalogMode: prefer

shellEmulator: true

trustPolicy: no-downgrade
catalog:
  '@schplitt/eslint-config': ^1.5.0
  better-result: ^2.7.0
  bumpp: ^11.1.0
  eslint: ^10.3.0
  hookable: ^6.1.1
  tsdown: ^0.22.0
  typescript: ^6.0.3
  vitest: ^4.1.5
onlyBuiltDependencies:
  - esbuild
